config/routes.rb
Rails.application.routes.draw do
  root 'links#index'

  resources :links do
    resources :comments, only: [:create, :destroy]
  end
  put '/upvote/:id', to: 'links#upvote', as: :upvote
  put '/downvote/:id', to: 'links#downvote', as: :downvote

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :link
end

app/models/link.rb
class Link < ActiveRecord::Base
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @link = Link.find(params[:link_id])
    @comment = @link.comments.build(comment_params)
    if @comment.save
      redirect_to link_path(params[:link_id])
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to link_path(params[:link_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :link_id)
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy, :upvote, :downvote]

  def show
    @comment = @link.comments.build
  end

  def index
    @links = Link.order(votes: :desc)
  end

  def new
    @link = Link.new
  end

  def create
    @link = Link.new(link_params)
    if @link.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @link.update_attributes(link_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @link.destroy
    redirect_to root_path
  end

  def upvote
    @link.votes += 1
    @link.save
    redirect_to root_path
  end

  def downvote
    @link.votes -= 1
    @link.save
    redirect_to root_path
  end

  private

  def link_params
    params.require(:link).permit(:title, :url, :votes)
  end

  def set_link
    @link = Link.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Breadit</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "New Link", new_link_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LinkAggregator</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navbar' %>
<div class='container'>
  <%= yield %>
</div>


</body>
</html>

app/views/links/_form.html.erb
<%= form_for @link do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :url %>
  <%= f.text_field :url %>

  <%= f.submit %>
<% end %>

app/views/links/edit.html.erb
<h1>Edit link</h1>

<%= render 'form' %>

<%= link_to "Back", root_path %>

app/views/links/index.html.erb
<h1>Front Page</h1>
<% @links.each do |link| %>
  <div class='well'>
    <h1><%= link_to link.title, link.url %></h1>
    <%= link.votes %>
    <%= link_to raw("<i class=\"glyphicon glyphicon-chevron-up\"> Upvote</i>"), upvote_path(link), class: "btn btn-success", method: :put %>
    <%= link_to raw("<i class=\"glyphicon glyphicon-chevron-down\"> Downvote</i>"), downvote_path(link), class: "btn btn-danger", method: :put %>
    <%= link_to raw("<i class=\"glyphicon glyphicon-comment\"> Comments</i>"), link_path(link), class: "btn btn-default" %>
  </div>
<% end %>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/links/show.html.erb
<h1><%= link_to @link.title, @link.url %></h1>
<h3>Votes: <%= @link.votes %></h3>

<h2>Comments</h2>
<% @link.comments.each do |comment| %>
  <div class='well'>
    <p><%= comment.body %></p>
  </div>
<% end %>

<h2>New Comment</h2>
<%= form_for [@link, @comment] do |f| %>
  <%= f.label :body %>
  <%= f.text_field :body %>

  <%= f.submit %>
<% end %>


<%= link_to 'Back to Front Page', root_path, class: 'btn btn-default' %>